// cadenceLibrary — kuratert oppgavebibliotek for Kadens-planlegger
// (Planning step 2).
//
// Hver oppgave er tilknyttet en lov/standard-paragraf, en kategori
// (governance/hms/risiko/...) og en standard-frekvens. Bruker velger hvilke
// som skal i planen, overstyrer frekvens/eier per oppgave, og iverksetter
// til task_items via createTask().
//
// I motsetning til den eksisterende /cadence-wizard som lagrer en
// cadence_plan med sub-tabeller, går /planlegging direkte til
// task_items (med recurrence_interval_days) for et lettvektig oppsett.

import type { CadenceCategoryId, CadenceOriginId } from './planningConstants'

export type CadenceLibraryItem = {
  id: string
  cat: CadenceCategoryId
  origin: CadenceOriginId
  title: string
  ref: string
  /** Lov-referanse-strenger som matcher law_refs[] ellers i systemet. */
  lawRefs: string[]
  /** Foreslått eier — display-tekst. */
  owner: string
  /** Standard varighet per forekomst (timer). */
  durationH: number
  /** Forutsetning / "før-du-starter"-tekst. */
  prerequisite?: string
  /** Standard frekvens-id. */
  freq:
    | 'ukentlig'
    | 'månedlig'
    | 'kvartalsvis'
    | 'halvårlig'
    | 'årlig'
    | 'toårig'
    | 'hendelse'
  /** Forventet antall forekomster per år (årlig=1, kvartalsvis=4 osv). */
  frequencyN: number
  /** Standard intervall i dager (matcher recurrence_interval_days). */
  intervalDays: number
  /** Standard anbefalt = true → vises som "Anbefalt" pill og kan auto-velges. */
  recommended: boolean
}

export const CADENCE_LIBRARY: CadenceLibraryItem[] = [
  // ── Governance / Styring & ledelse ───────────────────────────────────────
  {
    id: 'tpl-amu-1',
    cat: 'governance',
    origin: 'aml',
    title: 'AMU-møte (kvartalsvis)',
    ref: 'AML § 7-2',
    lawRefs: ['AML § 7-2'],
    owner: 'Hovedverneombud',
    durationH: 2,
    prerequisite: 'Saksliste 7 dager før',
    freq: 'kvartalsvis',
    frequencyN: 4,
    intervalDays: 90,
    recommended: true,
  },
  {
    id: 'tpl-amu-2',
    cat: 'governance',
    origin: 'aml',
    title: 'AMU årsrapport',
    ref: 'AML § 7-2',
    lawRefs: ['AML § 7-2'],
    owner: 'Hovedverneombud',
    durationH: 6,
    prerequisite: 'Alle 4 møter avholdt',
    freq: 'årlig',
    frequencyN: 1,
    intervalDays: 365,
    recommended: true,
  },
  {
    id: 'tpl-gov-1',
    cat: 'governance',
    origin: 'iso45001',
    title: 'Ledelsens gjennomgåelse',
    ref: 'ISO 45001 § 9.3',
    lawRefs: ['ISO 45001 § 9.3', 'AML § 3-1'],
    owner: 'Daglig leder',
    durationH: 4,
    prerequisite: 'KPI-rapport + revisjonsrapport',
    freq: 'årlig',
    frequencyN: 1,
    intervalDays: 365,
    recommended: true,
  },
  {
    id: 'tpl-gov-2',
    cat: 'governance',
    origin: 'ik',
    title: 'HMS-policy revideres',
    ref: 'IK-f § 5 nr. 4',
    lawRefs: ['IK-f § 5 nr. 4'],
    owner: 'Daglig leder',
    durationH: 3,
    prerequisite: 'Innspill fra AMU',
    freq: 'årlig',
    frequencyN: 1,
    intervalDays: 365,
    recommended: true,
  },
  {
    id: 'tpl-gov-3',
    cat: 'governance',
    origin: 'aml',
    title: 'Verneombudsvalg',
    ref: 'AML § 6-1',
    lawRefs: ['AML § 6-1'],
    owner: 'Hovedverneombud',
    durationH: 8,
    prerequisite: 'Valgkomité oppnevnt',
    freq: 'toårig',
    frequencyN: 0.5,
    intervalDays: 730,
    recommended: true,
  },

  // ── HMS / Kontroller ─────────────────────────────────────────────────────
  {
    id: 'tpl-hms-1',
    cat: 'hms',
    origin: 'aml',
    title: 'Vernerunde per lokasjon',
    ref: 'AML § 3-1',
    lawRefs: ['AML § 3-1', 'AML § 4-1', 'IK-f § 5 nr. 6'],
    owner: 'Verneombud',
    durationH: 3,
    prerequisite: 'Sjekkliste per lokasjon',
    freq: 'kvartalsvis',
    frequencyN: 4,
    intervalDays: 90,
    recommended: true,
  },
  {
    id: 'tpl-hms-2',
    cat: 'hms',
    origin: 'ik',
    title: 'Lovregister-gjennomgang',
    ref: 'IK-f § 5 nr. 1',
    lawRefs: ['IK-f § 5 nr. 1'],
    owner: 'HMS-leder',
    durationH: 4,
    prerequisite: 'Lovdata-abonnement',
    freq: 'halvårlig',
    frequencyN: 2,
    intervalDays: 182,
    recommended: true,
  },
  {
    id: 'tpl-hms-3',
    cat: 'hms',
    origin: 'iso45001',
    title: 'HMS-KPI-rapport (H1, F, fravær)',
    ref: 'ISO 45001 § 9.1',
    lawRefs: ['ISO 45001 § 9.1', 'AML § 3-1'],
    owner: 'HMS-leder',
    durationH: 1,
    prerequisite: 'Data fra Visma + avviksregister',
    freq: 'månedlig',
    frequencyN: 12,
    intervalDays: 30,
    recommended: true,
  },
  {
    id: 'tpl-hms-4',
    cat: 'hms',
    origin: 'ik',
    title: 'Avviksbehandling — restanse-rydd',
    ref: 'IK-f § 5 nr. 7',
    lawRefs: ['IK-f § 5 nr. 7'],
    owner: 'HMS-leder',
    durationH: 1,
    prerequisite: 'Avvik som er > 30 dager åpne',
    freq: 'månedlig',
    frequencyN: 12,
    intervalDays: 30,
    recommended: true,
  },

  // ── Risiko ───────────────────────────────────────────────────────────────
  {
    id: 'tpl-risk-1',
    cat: 'risiko',
    origin: 'aml',
    title: 'Årlig ROS-analyse',
    ref: 'AML § 3-1',
    lawRefs: ['AML § 3-1', 'IK-f § 5 nr. 6'],
    owner: 'HMS-leder',
    durationH: 8,
    prerequisite: 'Workshop med ledere + VO',
    freq: 'årlig',
    frequencyN: 1,
    intervalDays: 365,
    recommended: true,
  },
  {
    id: 'tpl-risk-2',
    cat: 'risiko',
    origin: 'aml',
    title: 'SJA-trening for risikoarbeid',
    ref: 'AML § 3-2',
    lawRefs: ['AML § 3-2'],
    owner: 'HMS-leder',
    durationH: 2,
    prerequisite: 'SJA-mal oppdatert',
    freq: 'halvårlig',
    frequencyN: 2,
    intervalDays: 182,
    recommended: true,
  },
  {
    id: 'tpl-risk-3',
    cat: 'risiko',
    origin: 'iso45001',
    title: 'Endringsledelse — HMS-vurdering',
    ref: 'ISO 45001 § 8.1.3',
    lawRefs: ['ISO 45001 § 8.1.3'],
    owner: 'HMS-leder',
    durationH: 0.5,
    prerequisite: 'Endringsforslag',
    freq: 'hendelse',
    frequencyN: 8,
    intervalDays: 45,
    recommended: true,
  },

  // ── Kompetanse ───────────────────────────────────────────────────────────
  {
    id: 'tpl-komp-1',
    cat: 'kompetanse',
    origin: 'aml',
    title: '40-timers HMS-grunnkurs (nye VO)',
    ref: 'AML § 6-5',
    lawRefs: ['AML § 6-5'],
    owner: 'HR-leder',
    durationH: 40,
    prerequisite: 'Påmelding via kursportal',
    freq: 'hendelse',
    frequencyN: 4,
    intervalDays: 90,
    recommended: true,
  },
  {
    id: 'tpl-komp-2',
    cat: 'kompetanse',
    origin: 'aml',
    title: 'HMS for ledere (lovpålagt)',
    ref: 'AML § 3-5',
    lawRefs: ['AML § 3-5'],
    owner: 'HR-leder',
    durationH: 14,
    prerequisite: 'Ledersamling i Q2',
    freq: 'hendelse',
    frequencyN: 7,
    intervalDays: 60,
    recommended: true,
  },
  {
    id: 'tpl-komp-3',
    cat: 'kompetanse',
    origin: 'egen',
    title: 'HMS-onboarding for nyansatte (30-dagers)',
    ref: 'AML § 3-2',
    lawRefs: ['AML § 3-2'],
    owner: 'HR-leder',
    durationH: 4,
    prerequisite: 'Onboarding-program',
    freq: 'hendelse',
    frequencyN: 24,
    intervalDays: 15,
    recommended: true,
  },
  {
    id: 'tpl-komp-4',
    cat: 'kompetanse',
    origin: 'egen',
    title: 'Lederopplæring i psykologisk trygghet',
    ref: 'AML § 4-3',
    lawRefs: ['AML § 4-3'],
    owner: 'HR-leder',
    durationH: 8,
    prerequisite: 'Ekstern fasilitator',
    freq: 'hendelse',
    frequencyN: 2,
    intervalDays: 182,
    recommended: true,
  },
  {
    id: 'tpl-komp-5',
    cat: 'kompetanse',
    origin: 'iso27001',
    title: 'Cyber-bevisstgjøring — alle ansatte',
    ref: 'ISO 27001 A.6.3',
    lawRefs: ['ISO 27001 A.6.3'],
    owner: 'IT-leder',
    durationH: 1,
    prerequisite: 'E-læringskampanje',
    freq: 'årlig',
    frequencyN: 1,
    intervalDays: 365,
    recommended: true,
  },

  // ── Medvirkning ──────────────────────────────────────────────────────────
  {
    id: 'tpl-med-1',
    cat: 'medvirkning',
    origin: 'aml',
    title: 'Medarbeiderundersøkelse',
    ref: 'AML § 4-3',
    lawRefs: ['AML § 4-3'],
    owner: 'HR-leder',
    durationH: 6,
    prerequisite: 'Forrige rapport gjennomgått',
    freq: 'halvårlig',
    frequencyN: 2,
    intervalDays: 182,
    recommended: true,
  },
  {
    id: 'tpl-med-2',
    cat: 'medvirkning',
    origin: 'aml',
    title: 'Pulsundersøkelse',
    ref: 'AML § 4-3',
    lawRefs: ['AML § 4-3'],
    owner: 'HR-leder',
    durationH: 1,
    prerequisite: 'Pulsverktøy oppe',
    freq: 'kvartalsvis',
    frequencyN: 4,
    intervalDays: 90,
    recommended: false,
  },
  {
    id: 'tpl-med-3',
    cat: 'medvirkning',
    origin: 'aml',
    title: 'Medarbeidersamtaler — runde',
    ref: 'AML § 4-2',
    lawRefs: ['AML § 4-2'],
    owner: 'HR-leder',
    durationH: 1,
    prerequisite: 'Mal + lederbrief',
    freq: 'årlig',
    frequencyN: 18,
    intervalDays: 20,
    recommended: true,
  },
  {
    id: 'tpl-med-4',
    cat: 'medvirkning',
    origin: 'egen',
    title: 'All-hands HMS-status',
    ref: 'AML § 4-2',
    lawRefs: ['AML § 4-2'],
    owner: 'HMS-leder',
    durationH: 1,
    prerequisite: 'KPI + årshjul',
    freq: 'kvartalsvis',
    frequencyN: 4,
    intervalDays: 90,
    recommended: false,
  },

  // ── Beredskap ────────────────────────────────────────────────────────────
  {
    id: 'tpl-ber-1',
    cat: 'beredskap',
    origin: 'iso45001',
    title: 'Brann- og evakueringsøvelse',
    ref: 'ISO 45001 § 8.2',
    lawRefs: ['ISO 45001 § 8.2', 'AML § 4-1'],
    owner: 'HMS-leder',
    durationH: 1,
    prerequisite: 'Brannvern-kontroll OK',
    freq: 'halvårlig',
    frequencyN: 2,
    intervalDays: 182,
    recommended: true,
  },
  {
    id: 'tpl-ber-2',
    cat: 'beredskap',
    origin: 'iso27001',
    title: 'Hendelseshåndtering — tabletop',
    ref: 'ISO 27001 A.5.29',
    lawRefs: ['ISO 27001 A.5.29'],
    owner: 'IT-leder',
    durationH: 4,
    prerequisite: 'Hendelse-scenario',
    freq: 'årlig',
    frequencyN: 1,
    intervalDays: 365,
    recommended: true,
  },
  {
    id: 'tpl-ber-3',
    cat: 'beredskap',
    origin: 'egen',
    title: 'Førstehjelps-trening',
    ref: 'AML § 4-1',
    lawRefs: ['AML § 4-1'],
    owner: 'HMS-leder',
    durationH: 4,
    prerequisite: 'Førstehjelpsinstruktør',
    freq: 'årlig',
    frequencyN: 1,
    intervalDays: 365,
    recommended: false,
  },

  // ── Medarbeidere & BHT ───────────────────────────────────────────────────
  {
    id: 'tpl-bht-1',
    cat: 'medarbeidere',
    origin: 'aml',
    title: 'BHT-handlingsplan revideres',
    ref: 'AML § 3-3',
    lawRefs: ['AML § 3-3'],
    owner: 'HMS-leder',
    durationH: 3,
    prerequisite: 'BHT-rapport',
    freq: 'årlig',
    frequencyN: 1,
    intervalDays: 365,
    recommended: true,
  },
  {
    id: 'tpl-bht-2',
    cat: 'medarbeidere',
    origin: 'aml',
    title: 'BHT-konsultasjoner — kvartalsmøte',
    ref: 'AML § 3-3',
    lawRefs: ['AML § 3-3'],
    owner: 'HMS-leder',
    durationH: 1,
    prerequisite: '—',
    freq: 'kvartalsvis',
    frequencyN: 4,
    intervalDays: 90,
    recommended: true,
  },
]
