import type { ReactElement } from 'react'
import { z } from 'zod'
import { InspectionModuleView, TasksModuleView, WorkflowModuleView } from './views'

export type RegisteredModuleRow = {
  id: string
  slug: string
  display_name: string
  is_active: boolean
  required_permissions: unknown
  [key: string]: unknown
}

export type RegisteredModuleComponentProps = {
  module: RegisteredModuleRow
  config: unknown
}

export type RegisteredModuleComponent = (props: RegisteredModuleComponentProps) => ReactElement

export type ModuleRegistryEntry = {
  moduleId: string
  slug: string
  description: string
  configSchema: z.ZodType<unknown>
  Component: RegisteredModuleComponent
}

const InspectionConfigSchema = z
  .object({
    summary: z
      .array(
        z.object({
          label: z.string(),
          value: z.string(),
          count: z.number().int().nonnegative().default(0),
        }),
      )
      .default([
        { label: 'Open rounds', value: 'open_rounds', count: 6 },
        { label: 'Critical findings', value: 'critical_findings', count: 2 },
        { label: 'Pending sign-off', value: 'pending_signoff', count: 3 },
      ]),
    rounds: z
      .array(
        z.object({
          id: z.string(),
          location: z.string(),
          frequency: z.string(),
          owner: z.string(),
          status: z.string(),
        }),
      )
      .default([
        {
          id: 'round-2026-04-001',
          location: 'Warehouse A',
          frequency: 'Weekly',
          owner: 'HSE Lead',
          status: 'active',
        },
        {
          id: 'round-2026-04-002',
          location: 'Production Line 2',
          frequency: 'Daily',
          owner: 'Shift Manager',
          status: 'scheduled',
        },
      ]),
  })
  .default({})

const WorkflowConfigSchema = z
  .object({
    rules: z
      .array(
        z.object({
          id: z.string(),
          trigger: z.string(),
          action: z.string(),
          module: z.string(),
          status: z.enum(['active', 'inactive']).default('active'),
        }),
      )
      .default([
        {
          id: 'wf-critical-finding',
          trigger: 'inspection.finding.severity=critical',
          action: 'create_deviation + create_task',
          module: 'inspection',
          status: 'active',
        },
        {
          id: 'wf-overdue-task',
          trigger: 'tasks.overdue=true',
          action: 'notify_owner',
          module: 'tasks',
          status: 'active',
        },
      ]),
  })
  .default({})

const TasksConfigSchema = z
  .object({
    queueName: z.string().default('Compliance tasks'),
    tasks: z
      .array(
        z.object({
          id: z.string(),
          title: z.string(),
          assignee: z.string(),
          due_date: z.string(),
          status: z.string(),
        }),
      )
      .default([
        {
          id: 'task-101',
          title: 'Verify corrective action for finding #872',
          assignee: 'Safety Coordinator',
          due_date: '2026-04-20',
          status: 'todo',
        },
        {
          id: 'task-102',
          title: 'Sign off Q2 inspection round',
          assignee: 'Operations Lead',
          due_date: '2026-04-18',
          status: 'in_progress',
        },
      ]),
  })
  .default({})

export const moduleRegistry: Record<string, ModuleRegistryEntry> = {
  inspection: {
    moduleId: 'inspection',
    slug: 'inspection',
    description: 'Inspection rounds, findings, and workflow-triggered actions.',
    configSchema: InspectionConfigSchema,
    Component: InspectionModuleView,
  },
  workflow: {
    moduleId: 'workflow',
    slug: 'workflow',
    description: 'Workflow rule definitions and event/action orchestration.',
    configSchema: WorkflowConfigSchema,
    Component: WorkflowModuleView,
  },
  tasks: {
    moduleId: 'tasks',
    slug: 'tasks',
    description: 'Task queue generated by user operations and automated workflows.',
    configSchema: TasksConfigSchema,
    Component: TasksModuleView,
  },
}

export const moduleSlugToRegistryId: Record<string, string> = {
  inspection: 'inspection',
  workflow: 'workflow',
  tasks: 'tasks',
  hse: 'inspection',
}

export function getModuleRegistryEntry(moduleId: string, moduleSlug: string): ModuleRegistryEntry | null {
  const idHit = moduleRegistry[moduleId]
  if (idHit) return idHit
  const mappedId = moduleSlugToRegistryId[moduleSlug]
  if (!mappedId) return null
  return moduleRegistry[mappedId] ?? null
}

export function parseModuleConfig(entry: ModuleRegistryEntry, config: unknown): unknown {
  const parsed = entry.configSchema.safeParse(config ?? {})
  if (parsed.success) return parsed.data
  return entry.configSchema.parse({})
}

export function resolveRegistryEntryForModule(module: RegisteredModuleRow): ModuleRegistryEntry | null {
  const candidateIds: string[] = []
  if (typeof module.id === 'string') candidateIds.push(module.id)
  if (typeof module.slug === 'string') candidateIds.push(module.slug)
  if (typeof module.module_id === 'string') candidateIds.push(module.module_id)

  for (const candidate of candidateIds) {
    const exact = moduleRegistry[candidate]
    if (exact) return exact
  }
  return getModuleRegistryEntry(String(module.id ?? ''), String(module.slug ?? ''))
}

export function coerceRequiredPermissions(input: unknown): string[] {
  if (Array.isArray(input)) {
    return input.filter((value): value is string => typeof value === 'string' && value.length > 0)
  }
  if (typeof input === 'string' && input.trim().length > 0) {
    const text = input.trim()
    if (text.startsWith('[') && text.endsWith(']')) {
      try {
        const parsed = JSON.parse(text) as unknown
        if (Array.isArray(parsed)) {
          return parsed.filter((value): value is string => typeof value === 'string' && value.length > 0)
        }
      } catch {
        // Fallback to comma-separated parsing.
      }
    }
    return text
      .split(',')
      .map((value) => value.trim())
      .filter((value) => value.length > 0)
  }
  return []
}

export function extractModuleConfig(module: RegisteredModuleRow): unknown {
  if (module.config !== undefined) return module.config
  if (module.module_config !== undefined) return module.module_config
  if (module.settings !== undefined) return module.settings
  return {}
}
