export type {
  SurveyPillar,
  SurveyQuestionSet,
  SurveyCampaignStatus,
  SurveyQuestionType,
  SurveyActionStatus,
  SurveyAmuStatus,
  SurveyCampaignRow,
  SurveyQuestionRow,
  SurveyResponseRow,
  SurveyResultRow,
  SurveyActionPlanRow,
  SurveyAmuReviewRow,
} from '../../data/survey'

export {
  normaliseLikert5,
  normaliseLikert7,
  QPS_NORDIC_QUESTIONS,
  ARK_QUESTIONS,
  PILLAR_LABEL,
  PILLAR_COLOR,
  PILLAR_LAW,
  STATUS_LABEL,
  STATUS_COLOR,
  ACTION_STATUS_LABEL,
  ACTION_STATUS_COLOR,
  scoreColor,
  scoreBg,
  scoreLabel,
} from '../../data/survey'
