/**
 * Reads supabase/seed-data/wiki-seed.json and writes supabase/migrations/archive/20260412120001_wiki_seed_data.sql
 * Run: npx tsx scripts/generate-wiki-seed-sql.ts
 */
import { readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')
const seed = JSON.parse(readFileSync(join(root, 'supabase/seed-data/wiki-seed.json'), 'utf8')) as {
  pageTemplates: Array<{
    id: string
    label: string
    description: string
    category: string
    legalBasis: string[]
    page: unknown
  }>
  legalCoverage: Array<{ ref: string; label: string; templateIds: string[] }>
}

function escLiteral(s: string): string {
  return s.replace(/'/g, "''")
}

const lines: string[] = []
lines.push('-- Generated by scripts/generate-wiki-seed-sql.ts — do not edit by hand')

for (const row of seed.legalCoverage) {
  const ids = row.templateIds.map((t) => `'${escLiteral(t)}'`).join(', ')
  lines.push(
    `insert into public.wiki_legal_coverage_items (ref, label, template_ids) values ('${escLiteral(row.ref)}', '${escLiteral(row.label)}', array[${ids}]::text[]) on conflict (ref) do update set label = excluded.label, template_ids = excluded.template_ids;`,
  )
}

let ord = 0
for (const t of seed.pageTemplates) {
  ord += 1
  const payload = JSON.stringify(t.page)
  const escaped = escLiteral(payload)
  lines.push(
    `insert into public.document_system_templates (id, slug, label, description, category, legal_basis, page_payload, sort_order) values (` +
      `'${escLiteral(t.id)}', '${escLiteral(t.id)}', '${escLiteral(t.label)}', '${escLiteral(t.description)}', ` +
      `'${escLiteral(t.category)}', array[${t.legalBasis.map((x) => `'${escLiteral(x)}'`).join(', ')}]::text[], ` +
      `'${escaped}'::jsonb, ${ord}` +
      `) on conflict (id) do update set label = excluded.label, description = excluded.description, category = excluded.category, legal_basis = excluded.legal_basis, page_payload = excluded.page_payload, sort_order = excluded.sort_order;`,
  )
}

const out = join(root, 'supabase/migrations/archive/20260412120001_wiki_seed_data.sql')
writeFileSync(out, lines.join('\n') + '\n', 'utf8')
console.log('Wrote', out, `(${lines.length} statements)`)
